spring.application.name=back
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/dbpadel
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.security.enabled=false

spring.jackson.time-zone=Europe/Madrid
